# Generated by Django 2.1.3 on 2019-01-18 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgLocation', models.ImageField(default='None', upload_to='segment')),
                ('species', models.CharField(default='None', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ImgParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgLocation', models.ImageField(default='None', upload_to='parent')),
            ],
        ),
        migrations.AddField(
            model_name='img',
            name='parentImage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.ImgParent'),
        ),
    ]
