# Generated by Django 2.1.3 on 2019-01-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='imgLocation',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='img',
            name='parentImage',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='img',
            name='species',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='img',
            name='img_url',
            field=models.ImageField(upload_to='raw_imgs'),
        ),
    ]
