# Generated by Django 2.1.3 on 2019-01-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='img_url',
        ),
        migrations.AddField(
            model_name='img',
            name='imgLocation',
            field=models.ImageField(default='None', upload_to='segment'),
        ),
        migrations.AddField(
            model_name='img',
            name='parentImage',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='img',
            name='species',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
