# Generated by Django 2.1.3 on 2019-01-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20190110_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='imgLocation',
        ),
        migrations.AlterField(
            model_name='img',
            name='img_url',
            field=models.ImageField(upload_to='segment'),
        ),
    ]
