# Generated by Django 2.1.3 on 2019-01-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foram',
        ),
    ]
